language: php

services:
  - elasticsearch

sudo: false

matrix:
  include:
    - php: 5.5
      env: PREFER="--prefer-lowest"
    - php: 5.5
      env: PREFER=""
    - php: 5.6
      env: PREFER=""
    - php: 7.0
      env: PREFER=""

before_script:
    - composer selfupdate
    - composer update $PREFER

script: 
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/behat --suite=zend_lucene
    - vendor/bin/behat --suite=elastic

cache:
  directories:
    - $HOME/.composer/cache
