language: php

services:
  - elasticsearch

sudo: false

php:
  - 5.6

before_script:
  - composer selfupdate
  - composer install

script: 
    - phpunit --coverage-text
    - vendor/bin/behat --suite=zend_lucene
    - vendor/bin/behat --suite=elastic
    - vendor/bin/phpbench run --report=all

env: 
  - SYMFONY_DEPRECATIONS_HELPER=weak
