language: php

services:
  - elasticsearch

sudo: false

php:
  - 5.6

before_script:
  - composer selfupdate
  - composer global require phpbench/phpbench dev-master
  - composer install

script: 
    - phpunit --coverage-text
    - vendor/bin/behat --suite=zend_lucene
    - vendor/bin/behat --suite=elastic
    - ~/.composer/vendor/bin/phpbench run --report=all
